version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image:  mongo:4.4
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
       - MONGO_INITDB_DATABASE=dd_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - mean-network

  # Node.js Backend API
  backend:
    image: tusharpol/mean-backend:latest
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/dd_db
      - PORT=8080    
    depends_on:
      - mongodb
    networks:
      - mean-network

  # Angular Frontend
  frontend:
    image: tusharpol/mean-frontend:latest 
    container_name: frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - mean-network

networks:
  mean-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
